@startuml ComputerClassDiagramCompact

title Классовая диаграмма: Иерархия компьютеров\nИнформационная система учета компьютерной техники

skinparam class {
    BackgroundColor White
    BorderColor Black
    FontSize 13
    AttributeFontSize 12
    MethodFontSize 12
}

skinparam package {
    BackgroundColor #F0F0F0
    BorderColor #666666
}

' Базовый класс
class Computer {
  {field} - brand[BRAND_LENGTH] : char
  {field} - screensize : float
  {field} - ram : int

  {method} + Computer()
  {method} + Computer(brand: string, screensize: float, ram: int)
  {method} + getBrand() : string
  {method} + getScreensize() : float
  {method} + getRam() : int
  {method} + setBrand(newBrand: string) : void
  {method} + setScreensize(newScreensize: float) : void
  {method} + setRam(newRam: int) : void

  {method} + get_info() : void <<virtual>>
  {method} + set_info() : void <<virtual>>
  {method} + print_header() : void <<virtual>>
  {method} + print_table() : void <<virtual>>
}

' Промежуточные классы
class Static_computer {
  {field} - power_supply : int

  {method} + getPowerSupply() : int
  {method} + setPowerSupply(newPowerSupply: int) : void

  {method} + get_info() : void <<override>>
  {method} + set_info() : void <<override>>
  {method} + print_header() : void <<override>>
  {method} + print_table() : void <<override>>
}

class Portable_computer {
  {field} - battery_life : int

  {method} + getBatteryLife() : int
  {method} + setBatteryLife(newBatteryLife: int) : void

  {method} + get_info() : void <<override>>
  {method} + set_info() : void <<override>>
  {method} + print_header() : void <<override>>
  {method} + print_table() : void <<override>>
}

' Конкретные классы
class Monoblock {
  {field} - has_touchscreen : bool

  {method} + getHasTouchscreen() : bool
  {method} + setHasTouchscreen(hasTouch: bool) : void

  {method} + get_info() : void <<override>>
  {method} + set_info() : void <<override>>
  {method} + print_header() : void <<override>>
  {method} + print_table() : void <<override>>
}

class Laptop {
  {field} - has_numeric_keypad : bool

  {method} + getHasNumericKeypad() : bool
  {method} + setHasNumericKeypad(hasKeypad: bool) : void

  {method} + get_info() : void <<override>>
  {method} + set_info() : void <<override>>
  {method} + print_header() : void <<override>>
  {method} + print_table() : void <<override>>
}

class Tablet {
  {field} - has_stylus : bool

  {method} + getHasStylus() : bool
  {method} + setHasStylus(stylus: bool) : void

  {method} + get_info() : void <<override>>
  {method} + set_info() : void <<override>>
  {method} + print_header() : void <<override>>
  {method} + print_table() : void <<override>>
}

' Отношения наследования
Computer <|-- Static_computer
Computer <|-- Portable_computer
Static_computer <|-- Monoblock
Portable_computer <|-- Laptop
Portable_computer <|-- Tablet

' Перегрузка операторов (отдельная заметка)
note "Операторы ввода/вывода:\noperator>> и operator<<\nреализованы как friend функции\nдля каждого класса" as OperatorsNote
OperatorsNote .. Computer
OperatorsNote .. Static_computer
OperatorsNote .. Portable_computer
OperatorsNote .. Monoblock
OperatorsNote .. Laptop
OperatorsNote .. Tablet

' Вспомогательные функции
note "Глобальные функции:\n- display_all_computers_table()\n\nГлобальные константы:\n- BRAND_LENGTH = 20\n- MAX_COMPUTERS = 100" as GlobalsNote

' Стили для визуализации
skinparam classBackgroundColor {
  Computer #E8F4FD
  Static_computer #F0F8FF
  Portable_computer #F0FFF0
  Monoblock #FFF0F5
  Laptop #FFF8DC
  Tablet #F5F5DC
}

@enduml