@startuml ComputerClassDiagramCompact

!theme plain

skinparam linetype ortho
skinparam classRoundCorner 0
skinparam classBorderThickness 2
skinparam classFontName "Times New Roman"
skinparam classFontSize 14
skinparam classFontStyle normal
skinparam classFontColor black
skinparam classAttributeIconSize 0
skinparam classBorderColor black
skinparam classBackgroundColor white
skinparam classArrowColor black
skinparam classAbstractFontStyle italic
skinparam classAbstractFontColor black
skinparam classAbstractUnderline true
skinparam inheritanceArrowColor black
hide circle

title Классовая диаграмма: Иерархия компьютеров\nИнформационная система учета компьютерной техники

' Базовый класс - вверху посередине
class Computer {
  {field} - brand[BRAND_LENGTH] : char
  {field} - screensize : float
  {field} - ram : int

  {method} + Computer()
  {method} + Computer(brand: string, screensize: float, ram: int)
  {method} + getBrand() : string
  {method} + getScreensize() : float
  {method} + getRam() : int
  {method} + setBrand(newBrand: string) : void
  {method} + setScreensize(newScreensize: float) : void
  {method} + setRam(newRam: int) : void

  {method} + get_info() : void <<virtual>>
  {method} + set_info() : void <<virtual>>
  {method} + print_header() : void <<virtual>>
  {method} + print_table() : void <<virtual>>
}

' Промежуточные классы
class Static_computer {
  {field} - power_supply : int

  {method} + getPowerSupply() : int
  {method} + setPowerSupply(newPowerSupply: int) : void

  {method} + get_info() : void <<override>>
  {method} + set_info() : void <<override>>
  {method} + print_header() : void <<override>>
  {method} + print_table() : void <<override>>
}

class Portable_computer {
  {field} - battery_life : int

  {method} + getBatteryLife() : int
  {method} + setBatteryLife(newBatteryLife: int) : void

  {method} + get_info() : void <<override>>
  {method} + set_info() : void <<override>>
  {method} + print_header() : void <<override>>
  {method} + print_table() : void <<override>>
}

' Конкретные классы
class Monoblock {
  {field} - has_touchscreen : bool

  {method} + getHasTouchscreen() : bool
  {method} + setHasTouchscreen(hasTouch: bool) : void

  {method} + get_info() : void <<override>>
  {method} + set_info() : void <<override>>
  {method} + print_header() : void <<override>>
  {method} + print_table() : void <<override>>
}

class Laptop {
  {field} - has_numeric_keypad : bool

  {method} + getHasNumericKeypad() : bool
  {method} + setHasNumericKeypad(hasKeypad: bool) : void

  {method} + get_info() : void <<override>>
  {method} + set_info() : void <<override>>
  {method} + print_header() : void <<override>>
  {method} + print_table() : void <<override>>
}

class Tablet {
  {field} - has_stylus : bool

  {method} + getHasStylus() : bool
  {method} + setHasStylus(stylus: bool) : void

  {method} + get_info() : void <<override>>
  {method} + set_info() : void <<override>>
  {method} + print_header() : void <<override>>
  {method} + print_table() : void <<override>>
}

' Простая структура с невидимыми связями
' Computer вверху
' Static_computer и Portable_computer на одном уровне ниже
' Monoblock под Static_computer, Laptop и Tablet под Portable_computer

Computer -[hidden]down- dummy1
dummy1 -[hidden]left- Static_computer
dummy1 -[hidden]right- Portable_computer

Static_computer -[hidden]down- Monoblock

Portable_computer -[hidden]down- dummy2
dummy2 -[hidden]left- Laptop
dummy2 -[hidden]right- Tablet

' Отношения наследования с прямыми углами
Computer -down-|> Static_computer
Computer -down-|> Portable_computer
Static_computer -down-|> Monoblock
Portable_computer -down-|> Laptop
Portable_computer -down-|> Tablet

hide dummy1
hide dummy2

' Перегрузка операторов (отдельная заметка)
note "Операторы ввода/вывода:\noperator>> и operator<<\nреализованы как friend функции\nдля каждого класса" as OperatorsNote
OperatorsNote .. Computer
OperatorsNote .. Static_computer
OperatorsNote .. Portable_computer
OperatorsNote .. Monoblock
OperatorsNote .. Laptop
OperatorsNote .. Tablet

' Вспомогательные функции
note "Глобальные функции:\n- display_all_computers_table()\n\nГлобальные константы:\n- BRAND_LENGTH = 20\n- MAX_COMPUTERS = 100" as GlobalsNote

@enduml